# Gateway info:
gateway.host=10.186.131.155
gateway.port=8183
gateway.name=gateway

# Queue Manager info:
queue.host=10.186.131.155
queue.port=8181
queue.name=urlqueue

# Barrel 1 info:
barrel1.host=10.186.131.155
barrel1.port=8182
barrel1.name=barrel1

# Barrel 2 info:
barrel2.host=10.186.131.90
barrel2.port=8184
barrel2.name=barrel2

# Barrel 3 info:
barrel3.host=10.186.131.90
barrel3.port=8185
barrel3.name=barrel3

# Barrel 4 info:
barrel4.host=10.186.131.90
barrel4.port=8186
barrel4.name=barrel4